apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: flask-api
  description: Python Flask API
  tags:
    - flask
    - python
spec:
  type: service
  lifecycle: production
  owner: engineering-team
  providesApis:
    - flask-api
  consumesApis:
    - other-service-api
