apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: flask-api
  description: This is the Flask API backend service.
spec:
  type: service
  lifecycle: production
  owner: your-team
  providesApis:
    - flask-api  # This is the API name, not the actual URL
  links:
    - url: "http://localhost:5000/swagger.json"
      title: "Flask API Documentation"

