apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: flask-api
  description: This is the Flask API backend service.
spec:
  type: service
  lifecycle: production
  owner: your-team
  providesApis:
    - openapi: http://127.0.0.1:5000/swagger.json
